# Generated by Django 3.0.3 on 2020-02-22 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the announcement', max_length=100)),
                ('summary', models.CharField(help_text='Summary of the event', max_length=1000)),
                ('date_of_event', models.DateField(help_text='Date of event')),
                ('timings', models.DateTimeField(help_text='Timings of the event')),
                ('venue', models.CharField(help_text='Venue of the event', max_length=100)),
                ('date_created', models.DateField(default=datetime.date.today, help_text='Date created')),
                ('date_of_expiry', models.DateField(help_text='Date of expiry')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Clubs')),
            ],
        ),
    ]
