# Generated by Django 3.0.3 on 2020-03-03 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_announcements_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Polls',
        ),
        migrations.AddField(
            model_name='clubs',
            name='description',
            field=models.CharField(default='', help_text='Few words about the club', max_length=1000),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date_of_expiry',
            field=models.DateField(default=datetime.timedelta, help_text='Date of expiry'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='summary',
            field=models.CharField(default='', help_text='Summary of the event', max_length=1000),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='timings',
            field=models.TimeField(help_text='Timings of the event'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(default='', help_text='Title for the announcement', max_length=100),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='venue',
            field=models.CharField(default='', help_text='Venue of the event', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='name',
            field=models.CharField(default='', help_text='Name of the club', max_length=100),
        ),
    ]
