# Generated by Django 3.0.3 on 2020-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200303_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the club', max_length=100, verbose_name='Name')),
                ('convener', models.CharField(help_text='Name of the convener', max_length=100, verbose_name='Convener')),
                ('email', models.EmailField(help_text='Club email id', max_length=1000, verbose_name='Email Id')),
                ('mobile_no', models.IntegerField(verbose_name='Mobile Number')),
                ('logo', models.ImageField(upload_to=None)),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('website', models.URLField(verbose_name='Website link')),
                ('technical', models.BooleanField(default=False)),
                ('exclusive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('description', models.CharField(help_text='short description of the event', max_length=500, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('venue', models.CharField(default='NULL', max_length=100, verbose_name='Venue')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the member', max_length=100, verbose_name='Name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('branch', models.CharField(max_length=100, verbose_name='Branch')),
                ('mobile_no', models.IntegerField(verbose_name='Mobile Number')),
                ('email', models.EmailField(help_text='Club email id', max_length=1000, verbose_name='Email Id')),
                ('roll_no', models.CharField(help_text='Branchwise Roll Number', max_length=8, verbose_name='Roll Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='club',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
