# Generated by Django 3.0.3 on 2020-03-05 05:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200304_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='club',
            new_name='club_id',
        ),
        migrations.AlterField(
            model_name='club',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Name of the club', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Name of the member', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
