# Generated by Django 3.0.3 on 2020-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20200305_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='about_us',
            field=models.CharField(default='', help_text='About the club', max_length=1000, verbose_name='About Us'),
        ),
    ]
